name: Build Spigot and Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPIGOT_VERSION: 1.21.4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download BuildTools
        run: |
          echo "Downloading BuildTools..."
          curl -O https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Run BuildTools
        run: |
          echo "Running BuildTools for Minecraft version ${{ env.SPIGOT_VERSION }}..."
          java -Xmx2G -jar BuildTools.jar --rev ${{ env.SPIGOT_VERSION }}
          echo "BuildTools finished."
          echo "Listing files to verify JAR:"
          ls -lh *.jar

      - name: Get Spigot JAR Filename
        id: get_jar
        run: |
          JAR_NAME=$(ls spigot-*.jar)
          if [ -z "$JAR_NAME" ]; then
            echo "::error::Spigot JAR file not found!"
            exit 1
          fi
          echo "Found JAR: $JAR_NAME"
          echo "filename=$JAR_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload JAR
        uses: ncipollo/release-action@v1
        with:

          artifacts: "${{ steps.get_jar.outputs.filename }}"

          tag: "spigot-${{ env.SPIGOT_VERSION }}-${{ github.run_number }}"

          name: "Spigot ${{ env.SPIGOT_VERSION }} (Build ${{ github.run_number }})"

          body: |
            Automated build of Spigot for Minecraft version ${{ env.SPIGOT_VERSION }}.
            Built JAR: ${{ steps.get_jar.outputs.filename }}
            Triggered by: ${{ github.event_name }}

          token: ${{ secrets.GITHUB_TOKEN }}

          draft: false
          prerelease: false

          allowUpdates: true
