name: Build Spigot and Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download BuildTools
        run: |
          curl -O https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Run BuildTools
        run: |
          java -jar BuildTools.jar --rev 1.21.5

      - name: Archive Generated JAR
        uses: actions/upload-artifact@v4
        with:
          name: spigot-1.21.5
          path: ./spigot-1.21.5.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spigot-1.21.5

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: spigot-1.21.5-${{ github.run_id }}
          release_name: Spigot 1.21.5 Build ${{ github.run_id }}
          body: |
            Spigot 1.21.5 build generated by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: spigot-1.21.5/spigot-1.21.5.jar
          asset_name: spigot-1.21.5.jar
          asset_content_type: application/java-archive
